export const universities = [
  "Universitas Indonesia",
  "Institut Teknologi Bandung",
  "Universitas Gadjah Mada",
  "Institut Pertanian Bogor",
  "Institut Teknologi Sepuluh Nopember",
  "Universitas Airlangga",
  "Universitas Brawijaya",
  "Universitas Diponegoro",
  "Universitas Padjadjaran",
  "Universitas Hasanuddin",
  "Universitas Sebelas Maret",
  "Universitas Andalas",
  "Universitas Sumatera Utara",
  "Universitas Pendidikan Indonesia",
  "Universitas Negeri Yogyakarta",
  "Universitas Negeri Malang",
  "Universitas Negeri Surabaya",
  "Universitas Negeri Jakarta",
  "Universitas Islam Indonesia",
  "Universitas Muhammadiyah Yogyakarta",
  "Universitas Muhammadiyah Malang",
  "Universitas Islam Negeri Syarif Hidayatullah Jakarta",
  "Universitas Islam Negeri Sunan Kalijaga Yogyakarta",
  "Universitas Islam Negeri Maulana Malik Ibrahim Malang",
  "Universitas Katolik Parahyangan",
  "Universitas Atma Jaya Yogyakarta",
  "Universitas Sanata Dharma",
  "Universitas Kristen Satya Wacana",
  "Universitas Kristen Petra",
  "Universitas Tarumanagara",
  "Universitas Trisakti",
  "Universitas Gunadarma",
  "Universitas Mercu Buana",
  "Universitas Pelita Harapan",
  "Universitas Bina Nusantara",
  "Universitas Telkom",
  "Universitas Esa Unggul",
  "Universitas Pembangunan Nasional Veteran Jakarta",
  "Universitas Pembangunan Nasional Veteran Yogyakarta",
  "Universitas Pembangunan Nasional Veteran Jawa Timur",
  "Universitas Negeri Semarang",
  "Universitas Negeri Medan",
  "Universitas Negeri Padang",
  "Universitas Negeri Makassar",
  "Universitas Negeri Gorontalo",
  "Universitas Negeri Manado",
  "Universitas Sam Ratulangi",
  "Universitas Tanjungpura",
  "Universitas Mulawarman",
  "Universitas Lambung Mangkurat",
  "Universitas Jember",
  "Universitas Mataram",
  "Universitas Udayana",
  "Universitas Nusa Cendana",
  "Universitas Pattimura",
  "Universitas Cenderawasih",
  "Universitas Papua",
];
